# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  Github:
    type: git
    url: https://github.com
    username: x-access-token
    token: ${{ secrets.SCL_DEPENDABOT_GH_TOKEN }}
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/London"
    target-branch: "develop"
    ignore:
      - dependency-name: 'FluentAssertions' #        ignore major-version updates FluentAssertions from version 8 and above
        versions: ['8.*', '9.*', '10.*', '11.*'] #   because FluentAssertions requires a paid license for corporate use
        # update-types: [ 'version-update:semver-major' ] 
  - package-ecosystem: "github-actions"
    directory: "/"
    registries:
      - Github
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/London"
    target-branch: "develop"
