# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "Laerdal.McuMgr.Tests/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/London"
    target-branch: "ksidirop/NOJIRA-fix-dependabot"
    ignore:
      - dependency-name: 'FluentAssertions' #        ignore major-version updates FluentAssertions from version 8 and above
        versions: ['8.*', '9.*', '10.*', '11.*'] #   because FluentAssertions requires a paid license for corporate use
        # update-types: [ 'version-update:semver-major' ] 

  - package-ecosystem: "nuget"
    directory: "Laerdal.McuMgr/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/London"
    target-branch: "ksidirop/NOJIRA-fix-dependabot"

  - package-ecosystem: "nuget"
    directory: "Laerdal.McuMgr.Bindings.Android/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/London"
    target-branch: "ksidirop/NOJIRA-fix-dependabot"

  - package-ecosystem: "nuget"
    directory: "Laerdal.McuMgr.Bindings.iOS/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/London"
    target-branch: "ksidirop/NOJIRA-fix-dependabot"

  - package-ecosystem: "nuget"
    directory: "Laerdal.McuMgr.Bindings.MacCatalyst/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/London"
    target-branch: "ksidirop/NOJIRA-fix-dependabot"

  - package-ecosystem: "nuget"
    directory: "Laerdal.McuMgr.Bindings.NetStandard/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/London"
    target-branch: "ksidirop/NOJIRA-fix-dependabot"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/London"
    target-branch: "ksidirop/NOJIRA-fix-dependabot"
