# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "02:00"
      timezone: "Europe/London"
    target-branch: "develop"
  
  #  - package-ecosystem: "nuget"
  #    directory: "Laerdal.McuMgr/" # disabled for now because it needs additional work to get it working
  #    schedule:
  #      interval: "weekly"
  #      time: "02:00"
  #      timezone: "Europe/London"
  #    target-branch: "develop"

  - package-ecosystem: "nuget"
    directory: "Laerdal.McuMgr.Bindings.Android/"
    schedule:
      interval: "weekly"
      time: "02:00"
      timezone: "Europe/London"
    target-branch: "develop"

  - package-ecosystem: "nuget"
    directory: "Laerdal.McuMgr.Bindings.iOS/"
    schedule:
      interval: "weekly"
      time: "02:00"
      timezone: "Europe/London"
    target-branch: "develop"

  - package-ecosystem: "nuget"
    directory: "Laerdal.McuMgr.Bindings.MacCatalyst/"
    schedule:
      interval: "weekly"
      time: "02:00"
      timezone: "Europe/London"
    target-branch: "develop"
  
  #  - package-ecosystem: "nuget"
  #    directory: "Laerdal.McuMgr.Bindings.NetStandard/" # no need
  #    schedule:
  #      interval: "daily"
  #      time: "02:00"
  #      timezone: "Europe/London"
  #    target-branch: "develop"

  - package-ecosystem: "nuget"
    directory: "Laerdal.McuMgr.Tests/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/London"
    target-branch: "develop"
    ignore:
      - dependency-name: 'FluentAssertions' #        ignore major-version updates FluentAssertions from version 8 and above
        versions: [ '8.*', '9.*', '10.*', '11.*' ] #   because FluentAssertions requires a paid license for corporate use
        # update-types: [ 'version-update:semver-major' ] 
